version: '2'
services:
  app:
    links:
      - db
    volumes:
      - ~/.m2:/root/.m2

    build:
      context: .

    
  db:
    hostname: localhost
    container_name: localhost
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: switchgroup3
      MYSQL_USER: root
      MYSQL_DATABASE: project_management
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3307:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080