version: '3'
services:
    mysqlsrv:
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=switchgroup3
        - MYSQL_DATABASE=project_management
      ports:
        - "3306:3306"

    backend:
      image : 1171473/switch-2017-g003:release-1-jun-2018-backend-mysql-v1
      ports:
        - "8080:8080"
      stdin_open: true
      tty: true

    frontend:
      image : 1171473/switch-2017-g003:release-1-jun-2018-frontend-mysql-v1
      ports:
        - "3000:3000"
